name: Build and push to pypi

on:
  repository_dispatch:
  push:

jobs:
  build:
      name: simpleelastix superbuild
      runs-on: macos-10.15
      steps:
          - name: checkout code
            uses: actions/checkout@v2
          - name: build
            run: $GITHUB_WORKSPACE/build-scripts/macos-10.15-build.sh
          - name: verify build
            run: python -c "import SimpleITK as sitk; sitk.ElastixImageFilter()"

# jobs:
#     build:
#         name: simpleelastix superbuild
#         runs-on: ubuntu-16.04
#         steps:
#             - name: checkout code
#               uses: actions/checkout@v2
#             - name: build
#               run: $GITHUB_WORKSPACE/build-scripts/ubuntu-16.04-build.sh
#             - name: verify build
#               run: python -c "import SimpleITK as sitk; sitk.ElastixImageFilter()"
